sudo: false
language: c
os:
  - linux
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
before_script:
  - set -e
  - git clone -b devel --depth 1 git://github.com/nim-lang/Nim.git
  - cd Nim
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - sed -i -e 's,cc = gcc,cc = clang,' config/nim.cfg
  - export PATH=$(pwd)/Nim/bin:$PATH

  - nim c koch
  - ./koch boot
  - ./koch boot -d:release
  - nim e install_nimble.nims
  - nimble update
  - cd ..
script:
  - nim c -d:release -r up2d8.nim
